environment:
  matrix:
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install test-unit codecov

build: off

test_script: test\unittest.rb
